""" The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? """

import time

def divisorGen(n):
    factors = list(factorGenerator(n))
    nfactors = len(factors)
    f = [0] * nfactors
    while True:
        yield reduce(lambda x, y: x*y, [factors[x][0]**f[x] for x in range(nfactors)], 1)
        i = 0
        while True:
            f[i] += 1
            if f[i] <= factors[i][1]:
                break
            f[i] = 0
            i += 1
            if i >= nfactors:
                return

def divisors(check_num):
	t0 = time.clock()
	divs = []
	cur_div = 1
	while cur_div <= (check_num / 2) + 1:
		if check_num % cur_div == 0:
			divs.append(cur_div)
		cur_div += 1
	divs.append(check_num)
	t1 = time.clock()
	print t1 - t0
	return divs


def ans(num):
	ind = 1
	ind_sum = 1
	while len(divisors(ind_sum)) < num:
		ind += 1
		ind_sum = ((ind * (ind + 1)) / 2)
	return ind_sum

print ans(10000000)