"""Consider all integer combinations of a^b for 2 <= a <= 5, 2 <= b <= 5.

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100, 2 <= b <= 100?"""

def distinct_powers(low_bound, high_bound):
	return len({pow(l_ind, h_ind) for l_ind in range(low_bound, high_bound + 1) for h_ind in range(low_bound, high_bound + 1)})

print distinct_powers(2, 100)